add verbose option
kiegroup/act-js pull request #46
Opened 2023-05-16 13:43 UTC by JoshMcCullough

To optionally enable verbose log output from Act.

2023-05-18 18:07 UTC, shubhbapna approved these changes
LGTM! Thank you!

2023-05-18 18:09 UTC, shubhbapna requested changes
Actually sorry could you also update the readme here:
https://github.com/kiegroup/act-js#run-a-job

2023-05-21 15:35 UTC, JoshMcCullough commented
Updated!

2023-05-24 03:18 UTC, shubhbapna approved these changes

2023-05-24 03:20 UTC, merged